---
name: Run pre-commit hooks
on: [push]
jobs:
  Run-Pre-Commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@v10.2.0
      - name: Run pre-commit
        run: uvx pre-commit run --all-files
